#!/bin/bash

# needs pactl

MUTE=$(pactl list sinks | grep '^[[:space:]]Mute:' | tail -n 1 | sed -e 's,.*Mute: ,,')
if [[ $MUTE == "yes" ]]; then
	echo "M"
else
	echo $(pactl list sinks | grep '^[[:space:]]Volume:' | \
		tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%
fi
